version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8001:8000"
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3001:80"
    restart: always 